### PR TITLE
Long: unsigned range fix

### PR DESCRIPTION
**Pull request by pluswave**
as always use uint64 in this context, specify unsigned = true in two cases.

### CODE REVIEW

**Comment by svk31** [comment]
This breaks one of the tests, but that's because the old test assumes a signed max value so I was able to fix that. All the other tests are fine so I assume this is safe to merge, but I'd appreciate an explantation of why  this context only requires unsigned ints

**Comment by pluswave** [comment]
a context to calculate tx_id. some nonce value is a large uint64 value, which makes the calculation wrong without this patch.

**Comment by svk31** [comment]
Ok, I fixed the test and merged it. Thanks

**Comment by svk31** [comment]
@pluswave I may need to revert this PR as it has broken call order updates which require negative ints. See discussion here: https://github.com/bitshares/bitshares-ui/issues/1194#issuecomment-372106743

**Pull request merged**
