### PR TITLE
update node to v16, and upgrade dependencies

### PR DESCRIPTION
**Pull request by xiangxn**
Among them, most of the tests have passed the test, and these two failed. Can you please take a look.
@sschiessl-bcp @abitmore 
test

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Ok, will check

**Comment by sschiessl-bcp** [comment]
Is this relevant https://github.com/bitshares/bitsharesjs-ws/issues/42#issuecomment-1007437145?

**Comment by xiangxn** [comment]
> Is this relevant [bitshares/bitsharesjs-ws#42 (comment)](https://github.com/bitshares/bitsharesjs-ws/issues/42#issuecomment-1007437145)?

No, that issue has been resolved.

**Comment by sschiessl-bcp** [comment]
> > Is this relevant [bitshares/bitsharesjs-ws#42 (comment)](https://github.com/bitshares/bitsharesjs-ws/issues/42#issuecomment-1007437145)?
> 
> No, that issue has been resolved.

I still get the error, how did you resolve it? If I add 
```
        ChainConfig.core_asset = "ABC";
        ChainConfig.address_prefix = "CBA";
```
everythwere we use `reset()` it works fine. The following 6.0.0 bitsharesws release will have a fix

**Comment by sschiessl-bcp** [comment]
> Among them, most of the tests have passed the test, and these two failed. Can you please take a look. @sschiessl-bcp @abitmore test

I don't get those errors btw

**Comment by xiangxn** [comment]
> > > Is this relevant [bitshares/bitsharesjs-ws#42 (comment)](https://github.com/bitshares/bitsharesjs-ws/issues/42#issuecomment-1007437145)?
> > 
> > 
> > No, that issue has been resolved.
> 
> I still get the error, how did you resolve it? If I add
> 
> ```
>         ChainConfig.core_asset = "ABC";
>         ChainConfig.address_prefix = "CBA";
> ```
> 
> everythwere we use `reset()` it works fine. The following 6.0.0 bitsharesws release will have a fix

I'm temporarily replacing all GPH

**Comment by xiangxn** [comment]
> > Among them, most of the tests have passed the test, and these two failed. Can you please take a look. @sschiessl-bcp @abitmore test
> 
> I don't get those errors btw

This problem appears to be caused by my network

**Comment by xiangxn** [comment]
If there are no problems, I would like to ask you to release a preview version. thanks

**Pull request merged**
